In [1]:
import pickle
import numpy as np
import pandas as pd

In [3]:
# Processing of gene PAV data

In [8]:
#Load file
genotype = pd.read_csv('../genotype/soybean_pan_pav.matrix_gene.txt', sep='\t', header=None, engine='c', low_memory=False)

In [9]:
genotype.head()

,0,1,2,3,4,5,6,7,8,9,...,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110
0,Individual,AB-01,AB-02,BR-01,BR-02,BR-03,BR-04,BR-05,BR-06,BR-07,...,USB-025,USB-026,USB-028,USB-031,USB-032,USB-033,USB-042,USB-043,USB-045,USB-046
1,GlymaLee.01G000100.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,GlymaLee.01G000200.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,GlymaLee.01G000300.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,GlymaLee.01G000400.1.v1.1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [15]:
gena_t = genotype.transpose()

In [16]:
gena_t.head()

,0,1,2,3,4,5,6,7,8,9,...,51405,51406,51407,51408,51409,51410,51411,51412,51413,51414
0,Individual,GlymaLee.01G000100.1.v1.1,GlymaLee.01G000200.1.v1.1,GlymaLee.01G000300.1.v1.1,GlymaLee.01G000400.1.v1.1,GlymaLee.01G000500.1.v1.1,GlymaLee.01G000600.1.v1.1,GlymaLee.01G000700.1.v1.1,GlymaLee.01G000800.1.v1.1,GlymaLee.01G000900.1.v1.1,...,UWASoyPan05304,UWASoyPan05305,UWASoyPan05306,UWASoyPan05309,UWASoyPan05310,UWASoyPan05311,UWASoyPan05312,UWASoyPan05313,UWASoyPan05314,UWASoyPan05315
1,AB-01,1,1,1,1,1,1,1,1,1,...,0,0,1,1,1,0,0,1,0,0
2,AB-02,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,1,0,0
3,BR-01,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,0,0,0
4,BR-02,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,0,0,0

In [19]:
gena_t.columns = gena_t.iloc[0]  # set first row as columns
gena_t = gena_t[1:]              # drop the first row

In [ ]:
genotype.reset_index(drop=True, inplace=True)

In [21]:
gena_t.set_index(gena_t.columns[0], inplace=True)

In [24]:
gena_t.index.name = "Data-storage-ID"

In [25]:
gena_t.head()

,GlymaLee.01G000100.1.v1.1,GlymaLee.01G000200.1.v1.1,GlymaLee.01G000300.1.v1.1,GlymaLee.01G000400.1.v1.1,GlymaLee.01G000500.1.v1.1,GlymaLee.01G000600.1.v1.1,GlymaLee.01G000700.1.v1.1,GlymaLee.01G000800.1.v1.1,GlymaLee.01G000900.1.v1.1,GlymaLee.01G001000.1.v1.1,...,UWASoyPan05304,UWASoyPan05305,UWASoyPan05306,UWASoyPan05309,UWASoyPan05310,UWASoyPan05311,UWASoyPan05312,UWASoyPan05313,UWASoyPan05314,UWASoyPan05315
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,1,1,1,0,0,1,0,0
AB-02,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,1,0,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,0,0,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,0,0,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,0,0,0,0

In [26]:
gena_t.to_pickle("pav_data.pkl")

In [2]:
from sklearn.feature_selection import VarianceThreshold

In [2]:
df = pd.read_pickle("gene_pav_data.pkl")

In [3]:
df.head()

,GlymaLee.01G000100.1.v1.1,GlymaLee.01G000200.1.v1.1,GlymaLee.01G000300.1.v1.1,GlymaLee.01G000400.1.v1.1,GlymaLee.01G000500.1.v1.1,GlymaLee.01G000600.1.v1.1,GlymaLee.01G000700.1.v1.1,GlymaLee.01G000800.1.v1.1,GlymaLee.01G000900.1.v1.1,GlymaLee.01G001000.1.v1.1,...,UWASoyPan05304,UWASoyPan05305,UWASoyPan05306,UWASoyPan05309,UWASoyPan05310,UWASoyPan05311,UWASoyPan05312,UWASoyPan05313,UWASoyPan05314,UWASoyPan05315
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,1,1,1,0,0,1,0,0
AB-02,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,1,0,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,0,0,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,1,0,0,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,1,0,0,0,0,0

In [6]:
selector = VarianceThreshold(threshold=0.01)

In [7]:
df_high_variance = selector.fit_transform(df)

In [8]:
df_high_variance.shape

(1110, 2918)

In [9]:
selected_features_mask = selector.get_support()

In [10]:
selected_feature_names = df.columns[selected_features_mask]

In [11]:
df_selected = pd.DataFrame(df_high_variance, columns=selected_feature_names, index=df.index)

In [12]:
df_selected.head()

,GlymaLee.01G000100.1.v1.1,GlymaLee.01G030900.1.v1.1,GlymaLee.01G034000.1.v1.1,GlymaLee.01G044800.1.v1.1,GlymaLee.01G044900.1.v1.1,GlymaLee.01G072000.1.v1.1,GlymaLee.01G073900.1.v1.1,GlymaLee.01G074000.1.v1.1,GlymaLee.01G076200.1.v1.1,GlymaLee.01G085600.1.v1.1,...,UWASoyPan05256,UWASoyPan05261,UWASoyPan05301,UWASoyPan05306,UWASoyPan05309,UWASoyPan05310,UWASoyPan05311,UWASoyPan05312,UWASoyPan05313,UWASoyPan05314
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,1,1,1,1,0,0,1,0
AB-02,1,0,1,1,1,1,1,1,1,1,...,1,0,1,1,0,1,0,1,1,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,1,0,1,1,0,1,0,1,0,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,1,1,0,1,0,1,0,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,1,0,1,1,0,1,0,0,0,0

In [13]:
df_selected.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1110 entries, AB-01 to USB-046
Columns: 2918 entries, GlymaLee.01G000100.1.v1.1 to UWASoyPan05314
dtypes: object(2918)
memory usage: 24.7+ MB

In [14]:
df_selected.to_pickle("gene_pav_afterFS_varthreshold.pkl")

In [9]:
df = pd.read_pickle("pfam_pav_newIDs_eval5.pkl")

In [10]:
df.head()

,PF02776_01G000400,PF04434_01G000700,PF10551_01G000700,PF03101_01G000800,PF04434_01G000800,PF10551_01G000800,PF09229_01G001000,PF03040_01G001100,PF13243_01G001300,PF13249_01G001300,...,PF00112_UWASoyPan05296,PF08246_UWASoyPan05296,PF03900_UWASoyPan05297,PF00957_UWASoyPan05299,PF13774_UWASoyPan05299,PF07651_UWASoyPan05301,PF01253_UWASoyPan05303,PF01657_UWASoyPan05311,PF00931_UWASoyPan05312,PF02427_UWASoyPan05315
Data-storage-ID,,,,,,,,,,,,,,,,,,,,,
AB-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0
AB-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-01,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-02,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,1,0
BR-03,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,0,0,0